# Generated by Django 3.2.4 on 2021-07-14 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('expiration_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Gram'), (3, 'Liter'), (4, 'Mililiter'), (5, 'Pieces')])),
                ('type', models.IntegerField(choices=[(1, 'no specific diet'), (2, 'vegetarian'), (3, 'vegan')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y%m&D/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_saver.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(through='food_saver.ProductUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
