# Generated by Django 3.2.4 on 2021-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y%m&D/'),
        ),
    ]
