# Generated by Django 3.2.4 on 2021-07-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Kilogram'), (2, 'Gram'), (3, 'Liter'), (4, 'Mililiter'), (5, 'Pieces')]),
        ),
        migrations.DeleteModel(
            name='ParticularUser',
        ),
    ]
