# Generated by Django 3.2.4 on 2021-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0005_auto_20210713_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularuser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
