# Generated by Django 3.2.4 on 2021-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0006_alter_particularuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
        migrations.AlterField(
            model_name='particularuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
