# Generated by Django 3.2.5 on 2021-07-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
