# Generated by Django 3.2.5 on 2021-07-15 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_saver', '0010_remove_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(through='food_saver.ProductUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
