# Generated by Django 3.2.5 on 2021-07-15 18:17

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0012_auto_20210715_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
