# Generated by Django 3.2.5 on 2021-07-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0020_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
