# Generated by Django 3.2.5 on 2021-07-18 13:14

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0021_auto_20210718_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
