# Generated by Django 3.2.5 on 2021-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0031_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'fruits and vegetables'), (2, 'processed food'), (3, 'sweets'), (4, 'liquids')]),
        ),
    ]
