# Generated by Django 3.2.5 on 2021-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0032_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'fruits and vegetables'), (2, 'processed food'), (3, 'sweets'), (4, 'liquids'), (5, 'meats'), (6, 'seafood'), (7, 'fish'), (8, 'juices'), (9, 'dry products'), (10, 'cleaning products')]),
        ),
    ]
