# Generated by Django 3.2.5 on 2021-07-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0033_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
